version: "3"

services:

  nginx:
    restart: always
    build: ./nginx
       
    ports:
      - '8081:80'   
    volumes:
      - ./client/public/images:/static 
  api:
    build: ./server
    ports:
      - "4000:4000"
    depends_on:
      - db
    container_name: blog-api
    env_file: 
        - ./server/.env
    volumes:
        - /app/node_modules
        - ./server/:/app

  client:
    build: ./client
    ports:
      - "3000:3000"
    container_name: blog-client
    stdin_open: true
    depends_on:
        - api
    volumes:
        - /app/node_modules
        - ./client/:/app
    links: 
        - api
    
  db:
    image: 'mongo:latest'
    # environment:
    #   - MONGO_INITDB_DATABASE=admin
    #   - MONGO_INITDB_ROOT_USERNAME=admin
    #   - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
