- hosts: lab
  remote_user: ec2-user
  become: yes
  tasks:
    # - name: Upgrade all packages
    #   yum: name=* state=latest


    - name: Add docker repo
      shell:  'dnf config-manager \
                  --add-repo \
                  https://download.docker.com/linux/centos/docker-ce.repo'

    - name: Install Docker
      package:
        name: docker-ce-3:18.09.1-3.el7
        state: latest

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
     
    - name: Download and install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.21.2/docker-compose-Linux-x86_64
        dest: /usr/bin/docker-compose
        mode: 0755

    - name: install system packages
      become: true
      yum:
        name:
          - python3
          - python3-devel
          - python3-pip
        state: present

    - name: install Python packages
      become: true
      pip:
        name:
          - virtualenv
        state: present
        executable: pip3

    - name: set system facts
      set_fact:
        python3_command: python3.6